root.bind('<KeyPress-w>', call_forward)
root.bind('<KeyPress-s>', call_back)
root.bind('<KeyPress-a>', call_left)
root.bind('<KeyPress-d>', call_right)

root.bind('<KeyPress-q>', call_left_side)
root.bind('<KeyPress-e>', call_right_side)
root.bind('<KeyRelease-q>', call_turn_stop)
root.bind('<KeyRelease-e>', call_turn_stop)

root.bind('<KeyRelease-w>', call_stop)
root.bind('<KeyRelease-s>', call_stop)
root.bind('<KeyRelease-a>', call_turn_stop)
root.bind('<KeyRelease-d>', call_turn_stop)

root.bind('<KeyPress-h>', call_head_home)
root.bind('<KeyPress-i>', call_head_up)
root.bind('<KeyPress-k>', call_head_down)
root.bind('<KeyPress-x>', call_find_color)
root.bind('<KeyPress-c>', call_watchdog)
root.bind('<KeyPress-b>', call_stream_audio)
root.bind('<KeyPress-j>', call_head_left)
root.bind('<KeyPress-l>', call_head_right)
root.bind('<KeyPress-u>', call_head_low)
root.bind('<KeyPress-o>', call_head_high)
root.bind('<KeyPress-z>', call_steady)
root.bind('<KeyPress-v>', call_smooth)
